# Generated by Django 5.2.8 on 2025-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=64, unique=True, verbose_name="用户名"),
                ),
                (
                    "email",
                    models.EmailField(max_length=128, unique=True, verbose_name="邮箱"),
                ),
                ("password", models.CharField(max_length=256, verbose_name="密码")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True, max_length=256, null=True, verbose_name="头像URL"
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "未知"), (1, "男"), (2, "女")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="个人简介"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="位置/所在地"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活/启用"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="是否管理员")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "正常"), (1, "禁用"), (2, "待审核")],
                        default=0,
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="信息最后更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
                "ordering": ["-created_time"],
            },
        ),
    ]
