"""
Django settings for egretwind project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path
import os
import yaml

import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# print(BASE_DIR)
logger = logging.getLogger('django')

LOCAL_CONFIG_PATH = os.path.join(BASE_DIR, 'config.yaml')

try:
    with open(LOCAL_CONFIG_PATH, 'r', encoding='utf-8') as f:
        # config: Dict
        config = yaml.safe_load(f)
    logger.info("配置加载成功")

except Exception as e:
    logger.critical(f"配置加载失败{e}")
    sys.exit(1)

required = ['DB_ENGINE', 'DB_NAME', 'DB_HOST', 'DB_USER', 'DB_PASSWORD', 'SECRET_KEY']
missing = [k for k in required if k not in config]
if missing:
    logger.critical(f"缺少配置： {', '.join(missing)}")
    sys.exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get("SECRET_KEY") or "zzw"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get("DEBUG", False)

# 根据 DEBUG 自动调整
if DEBUG:
    ALLOWED_HOSTS = ['*']  # 开发环境允许所有
else:
    ALLOWED_HOSTS = config.get('ALLOWED_HOSTS', ['localhost', '127.0.0.1', '118.25.77.231'])

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "user",
    # "article",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# REST_FRAMEWORK = {
#     # 'EXCEPTION_HANDLER': 'common.exception.handle_exception.handle_exception',
#     # # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
#     # 'DEFAULT_AUTHENTICATION_CLASSES': ['common.auth.authenticate.AnonymousAuthentication']
# }

ROOT_URLCONF = "egretwind.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "egretwind.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config['DB_ENGINE'],
        'NAME': config['DB_NAME'],
        'USER': config['DB_USER'],
        'PASSWORD': str(config['DB_PASSWORD']),
        'HOST': config['DB_HOST'],
        'PORT': str(config.get('DB_PORT', 3306)),
        'OPTIONS': config.get('DB_OPTIONS', {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        })
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # 生产环境收集静态文件的位置

# 媒体文件配置（用户上传的文件）
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
