# Generated by Django 5.2.8 on 2025-11-27 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="article",
            table="articles",
        ),
    ]
